# TeamManager Configuration

# Team settings
teams:
  # Maximum number of players in a team (0 = unlimited)
  max-players: 0
  
  # Whether to allow friendly fire within teams by default for new teams
  default-pvp-enabled: false
  
  # Team name restrictions
  name:
    min-length: 3
    max-length: 16
    # Regex pattern for allowed team names (letters, numbers, and underscores)
    pattern: '^[a-zA-Z0-9_]{3,16}$'

# Chat settings
chat:
  # Format for team chat messages
  # Available placeholders: {player}, {team}, {message}
  format: '&b[Team Chat] &e{player}&f: {message}'
  
  # Whether to also send team chat messages to console
  log-to-console: true 