name: TeamManager
version: 1.0.0
main: com.darkangel.teammanager.TeamManager
api-version: 1.20
description: Team management plugin for Paper/Spigot Minecraft servers
author: darkangel
website: https://github.com/darkangel/teammanager

commands:
  team:
    description: Main command for team management
    usage: /team <subcommand> [args]
    aliases: [t]
  tc:
    description: Send a message to your team
    usage: /tc <message>
    aliases: [teamchat]

permissions:
  teammanager.team.*:
    description: Gives access to all team commands
    default: true
    children:
      teammanager.team.create: true
      teammanager.team.disband: true
      teammanager.team.invite: true
      teammanager.team.join: true
      teammanager.team.leave: true
      teammanager.team.kick: true
      teammanager.team.pvp: true
      teammanager.team.info: true
      teammanager.team.list: true
      teammanager.team.chat: true
      teammanager.team.promote: true
  
  teammanager.team.create:
    description: Allows creation of teams
    default: true
  
  teammanager.team.disband:
    description: Allows disbanding of teams (as owner)
    default: true
  
  teammanager.team.invite:
    description: Allows inviting players to teams (as owner or recruiter)
    default: true
  
  teammanager.team.join:
    description: Allows joining teams with invites
    default: true
  
  teammanager.team.leave:
    description: Allows leaving teams
    default: true
  
  teammanager.team.kick:
    description: Allows kicking players from teams (as owner or recruiter)
    default: true
  
  teammanager.team.pvp:
    description: Allows toggling team PvP (as owner)
    default: true
  
  teammanager.team.info:
    description: Allows viewing team information
    default: true
  
  teammanager.team.list:
    description: Allows listing all teams
    default: true
  
  teammanager.team.chat:
    description: Allows using team chat
    default: true
    
  teammanager.team.promote:
    description: Allows promoting team members to recruiters (as owner)
    default: true 